variables:
    PROJECT_NAME: "kwetter_kweetservice"
    PROJECT_VERSION: "latest"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
    DOCKER_REPOSITORY: "kwetter-kweetservice"
    DOCKER_USERNAME: "mvandesanden"
    DOCKER_PASSWORD: "Password@"

include:
    - project: "I409368/ci_pipelines"
      file: ".maven-ci.yml"
      ref: "master"