steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]

  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "eu.gcr.io/kwetter-313614/kweetservice", "--build-arg=JAR_FILE=target/kweetservice-0.0.1-SNAPSHOT.jar", "."]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --location=europe-west4
      - --cluster=kwetter-cluster

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - rollout
      - restart
      - deployment
      - kweetservice
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"

substitutions:
  _CLUSTER_NAME: kwetter-cluster
  _COMPUTE_ZONE: europe-west4

images: ["eu.gcr.io/kwetter-313614/kweetservice"]