server:
  port: 8043
  servlet:
    contextPath: /api

spring:
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:h2:mem:testdb
#    username: compose-postgres
    username: sa
#    password: compose-postgres
    password:
    initialization-mode: always
  messaging:
    host: localhost
    password: guest
    port: 5672
    username: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey